### ISSUE TITLE
Please add Fedora 27 to supported distributions

### ISSUE THREAD

**Issue by jarun** [BytePackager/packagecore#122]
Fedora 27 has been released last Nov. Please add it to distributions.py.

**Comment by jarun** [comment]
Is this in production yet? I get the following error while generating RPM for Fedora 27:

```
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/bin/packagecore", line 11, in <module>
    sys.exit(main())
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/packagecore/__main__.py", line 126, in main
    if packager.run():
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/packagecore/packager.py", line 140, in run
    build = BUILDS[osName]
KeyError: 'fedora27'

travis_time:end:0be57eea:start=1514822327192834001,finish=1514822856213676138,duration=529020842137
[0K
[31;1mThe command "packagecore -o dist/ "${TRAVIS_TAG#v}"" failed and exited with 1 during .[0m

Your build has been stopped.
```

Complete logs: https://api.travis-ci.org/v3/job/323791155/log.txt

**Comment by jarun** [comment]
OK... I see it's still in progress.

**Comment by dlasalle** [comment]
I'm still working on it, but just an update: the fedora 27 docker container keeps failing to download its packages. I'm able to pull the link manually, so I'm not sure what the issue is.

```
Building package for fedora27: 
      name: packagecore-test
      version: 1.2.3
      releaseNum: 4
      maintainer: dominique@bytepackager.com
      license: GPL2
      homepage: https://bytepackager.com
      summary: Utility for generating Linux packages.
      os: fedora27
      buildDeps: ['gcc']
      runDeps: []
      preCompileCommands: 
      compileCommands: gcc test.c -o test
      installCommands: install -D -m 755 test "${BP_DESTDIR}/var/tmp/test"
      postInstallCommands: 
      testInstallCommands: ls "${BP_PACKAGE_FILE}" || exit 1
ls /var/tmp/test || exit 1
/var/tmp/test || exit 1
      
27: Pulling from library/fedora
Digest: sha256:25f7dac76b2c88d8b7e0b1d6213d3406e77c7f230bfa1e66bd1cbb81a944eaaf
Status: Image is up to date for fedora:27
Starting docker container 'packagecore-b1fdc2140190a10b'.
8e6552a99cb5        fedora:27           "tail -f /dev/null"   4 seconds ago       Up Less than a second                       packagecore-b1fdc2140190a10b
Using shared directory '/tmp/packagecore-b1fdc2140190a10b' and source directory '/tmp/packagecore-b1fdc2140190a10b/src'.
Fedora 27 - x86_64 - Updates                    813 kB/s |  15 MB     00:18    
Fedora 27 - x86_64                              1.2 MB/s |  58 MB     00:48    
Last metadata expiration check: 0:00:13 ago on Fri Jan  5 04:13:32 2018.
Package dnf-2.7.3-1.fc27.noarch is already installed, skipping.
Package make-1:4.2.1-4.fc27.x86_64 is already installed, skipping.
Dependencies resolved.
================================================================================
 Package                      Arch       Version              Repository   Size
================================================================================
Installing:
 dnf-plugins-core             noarch     2.1.5-1.fc27         fedora       51 k
 rpm-build                    x86_64     4.14.0-2.fc27        fedora      160 k
 rpmrebuild                   noarch     2.11-7.fc27          fedora       80 k
 which                        x86_64     2.21-4.fc27          fedora       46 k
Installing dependencies:
 binutils                     x86_64     2.29-6.fc27          fedora      5.9 M
 bzip2                        x86_64     1.0.6-24.fc27        fedora       58 k
 cmake-rpm-macros             noarch     3.10.1-4.fc27        updates      36 k
 cpio                         x86_64     2.12-6.fc27          fedora      262 k
 dwz                          x86_64     0.12-5.fc27          fedora      106 k
 elfutils                     x86_64     0.170-1.fc27         fedora      310 k
 fedora-rpm-macros            noarch     26-3.fc27            fedora      6.7 k
 file                         x86_64     5.31-10.fc27         fedora       71 k
 findutils                    x86_64     1:4.6.0-14.fc27      fedora      522 k
 fpc-srpm-macros              noarch     1.1-3.fc27           fedora      7.1 k
 gdb-headless                 x86_64     8.0.1-33.fc27        updates     3.3 M
 ghc-srpm-macros              noarch     1.4.2-6.fc27         fedora      7.9 k
 gnat-srpm-macros             noarch     4-4.fc27             fedora      8.4 k
 go-srpm-macros               noarch     2-10.fc27            fedora      8.0 k
 libbabeltrace                x86_64     1.5.3-1.fc27         fedora      195 k
 libipt                       x86_64     1.6.1-4.fc27         fedora       47 k
 libpkgconf                   x86_64     1.3.12-1.fc27        updates      31 k
 ocaml-srpm-macros            noarch     5-2.fc27             fedora      7.8 k
 openblas-srpm-macros         noarch     2-2.fc27             fedora      6.6 k
 patch                        x86_64     2.7.5-6.fc27         fedora      123 k
 perl-srpm-macros             noarch     1-24.fc27            fedora      9.3 k
 pkgconf                      x86_64     1.3.12-1.fc27        updates      31 k
 pkgconf-m4                   noarch     1.3.12-1.fc27        updates      13 k
 pkgconf-pkg-config           x86_64     1.3.12-1.fc27        updates      13 k
 python-srpm-macros           noarch     3-23.fc27            updates     9.7 k
 python3-dnf-plugins-core     noarch     2.1.5-1.fc27         fedora      141 k
 qt5-srpm-macros              noarch     5.9.1-2.fc27         fedora      8.5 k
 redhat-rpm-config            noarch     67-2.fc27            updates      62 k
 rust-srpm-macros             noarch     4-3.fc27             fedora      7.7 k
 unzip                        x86_64     6.0-36.fc27          fedora      189 k
 xz                           x86_64     5.2.3-4.fc27         fedora      150 k
 zip                          x86_64     3.0-20.fc27          fedora      270 k
 zstd                         x86_64     1.3.3-1.fc27         updates     306 k

Transaction Summary
================================================================================
Install  37 Packages

Total download size: 13 M
Installed size: 43 M
Downloading Packages:
(1/37): dnf-plugins-core-2.1.5-1.fc27.noarch.rp 9.0 kB/s |  51 kB     00:05    
(2/37): rpmrebuild-2.11-7.fc27.noarch.rpm        14 kB/s |  80 kB     00:05    
(3/37): which-2.21-4.fc27.x86_64.rpm            455 kB/s |  46 kB     00:00    
(4/37): rpm-build-4.14.0-2.fc27.x86_64.rpm       26 kB/s | 160 kB     00:06    
(5/37): bzip2-1.0.6-24.fc27.x86_64.rpm           72 kB/s |  58 kB     00:00    
(6/37): cpio-2.12-6.fc27.x86_64.rpm             513 kB/s | 262 kB     00:00    
(7/37): file-5.31-10.fc27.x86_64.rpm            255 kB/s |  71 kB     00:00    
(8/37): elfutils-0.170-1.fc27.x86_64.rpm        304 kB/s | 310 kB     00:01    
(9/37): patch-2.7.5-6.fc27.x86_64.rpm           387 kB/s | 123 kB     00:00    
(10/37): xz-5.2.3-4.fc27.x86_64.rpm             435 kB/s | 150 kB     00:00    
(11/37): findutils-4.6.0-14.fc27.x86_64.rpm     353 kB/s | 522 kB     00:01    
(12/37): python3-dnf-plugins-core-2.1.5-1.fc27. 440 kB/s | 141 kB     00:00    
(13/37): libbabeltrace-1.5.3-1.fc27.x86_64.rpm  603 kB/s | 195 kB     00:00    
(14/37): libipt-1.6.1-4.fc27.x86_64.rpm         455 kB/s |  47 kB     00:00    
(15/37): binutils-2.29-6.fc27.x86_64.rpm        843 kB/s | 5.9 MB     00:07    
(16/37): pkgconf-pkg-config-1.3.12-1.fc27.x86_6 2.7 kB/s |  13 kB     00:04    
(17/37): pkgconf-m4-1.3.12-1.fc27.noarch.rpm    198 kB/s |  13 kB     00:00    
(18/37): pkgconf-1.3.12-1.fc27.x86_64.rpm        34 kB/s |  31 kB     00:00    
(19/37): libpkgconf-1.3.12-1.fc27.x86_64.rpm    307 kB/s |  31 kB     00:00    
(20/37): redhat-rpm-config-67-2.fc27.noarch.rpm 210 kB/s |  62 kB     00:00    
(21/37): cmake-rpm-macros-3.10.1-4.fc27.noarch. 150 kB/s |  36 kB     00:00    
(22/37): fedora-rpm-macros-26-3.fc27.noarch.rpm  56 kB/s | 6.7 kB     00:00    
(23/37): fpc-srpm-macros-1.1-3.fc27.noarch.rpm   73 kB/s | 7.1 kB     00:00    
(24/37): dwz-0.12-5.fc27.x86_64.rpm             370 kB/s | 106 kB     00:00    
(25/37): ghc-srpm-macros-1.4.2-6.fc27.noarch.rp  62 kB/s | 7.9 kB     00:00    
(26/37): gnat-srpm-macros-4-4.fc27.noarch.rpm    76 kB/s | 8.4 kB     00:00    
(27/37): go-srpm-macros-2-10.fc27.noarch.rpm     94 kB/s | 8.0 kB     00:00    
(28/37): ocaml-srpm-macros-5-2.fc27.noarch.rpm   89 kB/s | 7.8 kB     00:00    
(29/37): openblas-srpm-macros-2-2.fc27.noarch.r  85 kB/s | 6.6 kB     00:00    
(30/37): perl-srpm-macros-1-24.fc27.noarch.rpm  114 kB/s | 9.3 kB     00:00    
(31/37): qt5-srpm-macros-5.9.1-2.fc27.noarch.rp 106 kB/s | 8.5 kB     00:00    
(32/37): rust-srpm-macros-4-3.fc27.noarch.rpm    97 kB/s | 7.7 kB     00:00    
(33/37): zstd-1.3.3-1.fc27.x86_64.rpm           361 kB/s | 306 kB     00:00    
(34/37): zip-3.0-20.fc27.x86_64.rpm             199 kB/s | 270 kB     00:01    
(35/37): python-srpm-macros-3-23.fc27.noarch.rp  78 kB/s | 9.7 kB     00:00    
(36/37): unzip-6.0-36.fc27.x86_64.rpm           261 kB/s | 189 kB     00:00    
(37/37): gdb-headless-8.0.1-33.fc27.x86_64.rpm  390 kB/s | 3.3 MB     00:08    
--------------------------------------------------------------------------------
Total                                           437 kB/s |  13 MB     00:29     
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                        1/1 
  Installing       : unzip-6.0-36.fc27.x86_64                              1/37 
  Installing       : cpio-2.12-6.fc27.x86_64                               2/37 
  Running scriptlet: cpio-2.12-6.fc27.x86_64                               2/37 
  Installing       : zip-3.0-20.fc27.x86_64                                3/37 
  Installing       : python-srpm-macros-3-23.fc27.noarch                   4/37 
  Installing       : zstd-1.3.3-1.fc27.x86_64                              5/37 
  Installing       : rust-srpm-macros-4-3.fc27.noarch                      6/37 
  Installing       : qt5-srpm-macros-5.9.1-2.fc27.noarch                   7/37 
  Installing       : perl-srpm-macros-1-24.fc27.noarch                     8/37 
  Installing       : openblas-srpm-macros-2-2.fc27.noarch                  9/37 
  Installing       : ocaml-srpm-macros-5-2.fc27.noarch                    10/37 
  Installing       : go-srpm-macros-2-10.fc27.noarch                      11/37 
  Installing       : gnat-srpm-macros-4-4.fc27.noarch                     12/37 
  Installing       : ghc-srpm-macros-1.4.2-6.fc27.noarch                  13/37 
  Installing       : fpc-srpm-macros-1.1-3.fc27.noarch                    14/37 
  Installing       : fedora-rpm-macros-26-3.fc27.noarch                   15/37 
  Installing       : dwz-0.12-5.fc27.x86_64                               16/37 
  Installing       : cmake-rpm-macros-3.10.1-4.fc27.noarch                17/37 
  Installing       : redhat-rpm-config-67-2.fc27.noarch                   18/37 
  Installing       : libpkgconf-1.3.12-1.fc27.x86_64                      19/37 
  Running scriptlet: libpkgconf-1.3.12-1.fc27.x86_64                      19/37 
  Installing       : pkgconf-1.3.12-1.fc27.x86_64                         20/37 
  Installing       : pkgconf-m4-1.3.12-1.fc27.noarch                      21/37 
  Installing       : pkgconf-pkg-config-1.3.12-1.fc27.x86_64              22/37 
  Installing       : libipt-1.6.1-4.fc27.x86_64                           23/37 
  Running scriptlet: libipt-1.6.1-4.fc27.x86_64                           23/37 
  Installing       : libbabeltrace-1.5.3-1.fc27.x86_64                    24/37 
  Running scriptlet: libbabeltrace-1.5.3-1.fc27.x86_64                    24/37 
  Installing       : gdb-headless-8.0.1-33.fc27.x86_64                    25/37 
  Installing       : python3-dnf-plugins-core-2.1.5-1.fc27.noarch         26/37 
  Installing       : xz-5.2.3-4.fc27.x86_64                               27/37 
  Installing       : patch-2.7.5-6.fc27.x86_64                            28/37 
  Installing       : findutils-1:4.6.0-14.fc27.x86_64                     29/37 
  Running scriptlet: findutils-1:4.6.0-14.fc27.x86_64                     29/37 
  Installing       : file-5.31-10.fc27.x86_64                             30/37 
  Installing       : elfutils-0.170-1.fc27.x86_64                         31/37 
  Installing       : bzip2-1.0.6-24.fc27.x86_64                           32/37 
  Installing       : binutils-2.29-6.fc27.x86_64                          33/37 
  Running scriptlet: binutils-2.29-6.fc27.x86_64                          33/37 
install-info: No such file or directory for /usr/share/info/as.info.gz
install-info: No such file or directory for /usr/share/info/binutils.info.gz
install-info: No such file or directory for /usr/share/info/gprof.info.gz
install-info: No such file or directory for /usr/share/info/ld.info.gz
  Installing       : rpm-build-4.14.0-2.fc27.x86_64                       34/37 
  Installing       : rpmrebuild-2.11-7.fc27.noarch                        35/37 
  Installing       : dnf-plugins-core-2.1.5-1.fc27.noarch                 36/37 
  Installing       : which-2.21-4.fc27.x86_64                             37/37 
  Running scriptlet: which-2.21-4.fc27.x86_64                             37/37 
install-info: No such file or directory for /usr/share/info/which.info.gz
  Verifying        : rpm-build-4.14.0-2.fc27.x86_64                        1/37 
  Verifying        : rpmrebuild-2.11-7.fc27.noarch                         2/37 
  Verifying        : dnf-plugins-core-2.1.5-1.fc27.noarch                  3/37 
  Verifying        : which-2.21-4.fc27.x86_64                              4/37 
  Verifying        : binutils-2.29-6.fc27.x86_64                           5/37 
  Verifying        : bzip2-1.0.6-24.fc27.x86_64                            6/37 
  Verifying        : cpio-2.12-6.fc27.x86_64                               7/37 
  Verifying        : elfutils-0.170-1.fc27.x86_64                          8/37 
  Verifying        : file-5.31-10.fc27.x86_64                              9/37 
  Verifying        : findutils-1:4.6.0-14.fc27.x86_64                     10/37 
  Verifying        : patch-2.7.5-6.fc27.x86_64                            11/37 
  Verifying        : xz-5.2.3-4.fc27.x86_64                               12/37 
  Verifying        : python3-dnf-plugins-core-2.1.5-1.fc27.noarch         13/37 
  Verifying        : gdb-headless-8.0.1-33.fc27.x86_64                    14/37 
  Verifying        : libbabeltrace-1.5.3-1.fc27.x86_64                    15/37 
  Verifying        : libipt-1.6.1-4.fc27.x86_64                           16/37 
  Verifying        : pkgconf-pkg-config-1.3.12-1.fc27.x86_64              17/37 
  Verifying        : pkgconf-1.3.12-1.fc27.x86_64                         18/37 
  Verifying        : pkgconf-m4-1.3.12-1.fc27.noarch                      19/37 
  Verifying        : libpkgconf-1.3.12-1.fc27.x86_64                      20/37 
  Verifying        : redhat-rpm-config-67-2.fc27.noarch                   21/37 
  Verifying        : cmake-rpm-macros-3.10.1-4.fc27.noarch                22/37 
  Verifying        : dwz-0.12-5.fc27.x86_64                               23/37 
  Verifying        : fedora-rpm-macros-26-3.fc27.noarch                   24/37 
  Verifying        : fpc-srpm-macros-1.1-3.fc27.noarch                    25/37 
  Verifying        : ghc-srpm-macros-1.4.2-6.fc27.noarch                  26/37 
  Verifying        : gnat-srpm-macros-4-4.fc27.noarch                     27/37 
  Verifying        : go-srpm-macros-2-10.fc27.noarch                      28/37 
  Verifying        : ocaml-srpm-macros-5-2.fc27.noarch                    29/37 
  Verifying        : openblas-srpm-macros-2-2.fc27.noarch                 30/37 
  Verifying        : perl-srpm-macros-1-24.fc27.noarch                    31/37 
  Verifying        : qt5-srpm-macros-5.9.1-2.fc27.noarch                  32/37 
  Verifying        : rust-srpm-macros-4-3.fc27.noarch                     33/37 
  Verifying        : zip-3.0-20.fc27.x86_64                               34/37 
  Verifying        : zstd-1.3.3-1.fc27.x86_64                             35/37 
  Verifying        : unzip-6.0-36.fc27.x86_64                             36/37 
  Verifying        : python-srpm-macros-3-23.fc27.noarch                  37/37 

Installed:
  dnf-plugins-core.noarch 2.1.5-1.fc27                                          
  rpm-build.x86_64 4.14.0-2.fc27                                                
  rpmrebuild.noarch 2.11-7.fc27                                                 
  which.x86_64 2.21-4.fc27                                                      
  binutils.x86_64 2.29-6.fc27                                                   
  bzip2.x86_64 1.0.6-24.fc27                                                    
  cmake-rpm-macros.noarch 3.10.1-4.fc27                                         
  cpio.x86_64 2.12-6.fc27                                                       
  dwz.x86_64 0.12-5.fc27                                                        
  elfutils.x86_64 0.170-1.fc27                                                  
  fedora-rpm-macros.noarch 26-3.fc27                                            
  file.x86_64 5.31-10.fc27                                                      
  findutils.x86_64 1:4.6.0-14.fc27                                              
  fpc-srpm-macros.noarch 1.1-3.fc27                                             
  gdb-headless.x86_64 8.0.1-33.fc27                                             
  ghc-srpm-macros.noarch 1.4.2-6.fc27                                           
  gnat-srpm-macros.noarch 4-4.fc27                                              
  go-srpm-macros.noarch 2-10.fc27                                               
  libbabeltrace.x86_64 1.5.3-1.fc27                                             
  libipt.x86_64 1.6.1-4.fc27                                                    
  libpkgconf.x86_64 1.3.12-1.fc27                                               
  ocaml-srpm-macros.noarch 5-2.fc27                                             
  openblas-srpm-macros.noarch 2-2.fc27                                          
  patch.x86_64 2.7.5-6.fc27                                                     
  perl-srpm-macros.noarch 1-24.fc27                                             
  pkgconf.x86_64 1.3.12-1.fc27                                                  
  pkgconf-m4.noarch 1.3.12-1.fc27                                               
  pkgconf-pkg-config.x86_64 1.3.12-1.fc27                                       
  python-srpm-macros.noarch 3-23.fc27                                           
  python3-dnf-plugins-core.noarch 2.1.5-1.fc27                                  
  qt5-srpm-macros.noarch 5.9.1-2.fc27                                           
  redhat-rpm-config.noarch 67-2.fc27                                            
  rust-srpm-macros.noarch 4-3.fc27                                              
  unzip.x86_64 6.0-36.fc27                                                      
  xz.x86_64 5.2.3-4.fc27                                                        
  zip.x86_64 3.0-20.fc27                                                        
  zstd.x86_64 1.3.3-1.fc27                                                      

Complete!
Using specfile:{
%define _build_name_fmt packagecore-test-1.2.3-4.rpm
%define _rpmdir /tmp/packagecore-b1fdc2140190a10b

Name: packagecore-test
Version: 1.2.3
Release: 4%{?dist}
Summary: Utility for generating Linux packages.
Group: other
License: GPL2
BuildRequires: gcc
Packager: dominique@bytepackager.com
URL: https://bytepackager.com

%description

%build
BP_DESTDIR="%{buildroot}"
BP_SOURCEDIR="/tmp/packagecore-b1fdc2140190a10b/src"
cd "/tmp/packagecore-b1fdc2140190a10b/src"
gcc test.c -o test
%install
BP_DESTDIR="%{buildroot}"
BP_SOURCEDIR="/tmp/packagecore-b1fdc2140190a10b/src"
cd "/tmp/packagecore-b1fdc2140190a10b/src"
install -D -m 755 test "${BP_DESTDIR}/var/tmp/test"
%files
/


}
Last metadata expiration check: 0:02:10 ago on Fri Jan  5 04:13:32 2018.
Dependencies resolved.
================================================================================
 Package              Arch         Version                  Repository     Size
================================================================================
Installing:
 gcc                  x86_64       7.2.1-2.fc27             fedora         21 M
Installing dependencies:
 cpp                  x86_64       7.2.1-2.fc27             fedora        9.2 M
 glibc-devel          x86_64       2.26-15.fc27             fedora        985 k
 glibc-headers        x86_64       2.26-15.fc27             fedora        500 k
 isl                  x86_64       0.16.1-3.fc27            fedora        835 k
 kernel-headers       x86_64       4.14.11-300.fc27         updates       1.2 M
 libgomp              x86_64       7.2.1-2.fc27             fedora        198 k
 libmpc               x86_64       1.0.2-8.fc27             fedora         56 k

Transaction Summary
================================================================================
Install  8 Packages

Total download size: 34 M
Installed size: 86 M
Downloading Packages:

The downloaded packages were saved in cache until the next successful transaction.
You can remove cached packages by executing 'dnf clean packages'.
Error: Error downloading packages:
  Curl error (28): Timeout was reached for https://mirrors.fedoraproject.org/metalink?repo=updates-released-f27&arch=x86_64 [Operation timed out after 30001 milliseconds with 0 out of 0 bytes received]
```

**Comment by jarun** [comment]
Thanks for the update @dlasalle!

**Comment by jarun** [comment]
Is there any possibility of getting this fixed by next weekend? I am overdue for a release. If 27 takes time I can make my release with Fedora 26.

Also, frequently the packaging fails due to https://github.com/BytePackager/packagecore/issues/125. Is that fixed yet?

**Comment by dlasalle** [comment]
I'm gonna try and get a version into PyPi tonight with Fedora 27, and the keyring updates. However, it looks like the arch docker image is getting out of date, so I'll try and get new one up into docker hub sometime this week (#128). Sorry for the delays on this.

**Comment by dlasalle** [comment]
This should work in 0.9.7 (just uploaded it to PyPI).
