### ISSUE TITLE
Package build fails for Fedora 26 and 27

### ISSUE THREAD

**Issue by jarun** [BytePackager/packagecore#132]
I am getting the following error when trying to build packages for Fedora 26 and 27:

```
...
Error: Failed to synchronize cache for repo 'updates'
Cleaning up self packagecore-e5f2837dc0ca8d18.
packagecore-e5f2837dc0ca8d18
packagecore-e5f2837dc0ca8d18

###########################################################
# Failed to build package for 'fedora26'.
###########################################################
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/packagecore/packager.py", line 160, in run
    imageName=build["dockerImage"])
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/packagecore/packager.py", line 101, in _build
    recipe.prep(container)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/packagecore/rpm.py", line 195, in prep
    "dnf-command(builddep)", "which", "make"])
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/packagecore/docker.py", line 149, in execute
    _checkedDockerCommand(["exec", self._name] + cmd)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/packagecore/docker.py", line 54, in _checkedDockerCommand
    raise DockerError("Command '%s' returned %d." % (cmd, status))
packagecore.docker.DockerError: Command '['exec', 'packagecore-e5f2837dc0ca8d18', '/usr/bin/dnf', 'install', '-y', 'dnf-command(repoquery)', 'rpm-build', 'rpmrebuild', 'dnf-command(builddep)', 'which', 'make']' returned 1.
```

The complete log is here:

https://api.travis-ci.org/v3/job/362392122/log.txt

**Comment by jarun** [comment]
Built properly on re-issue. Probably an intermittent problem. Closing the issue.

**Comment by dlasalle** [comment]
I'm gonna leave this open because if it is just a error with a mirror timing out, it would at least be nice to have a better error message.

The log you attached appears to be from a successful run (it shows Fedora 26 and 27 building correctly). If you have the log with the error handy, can you attach it?

**Comment by jarun** [comment]
I think it got overwritten after I restarted the build. I will update if I see this again.

**Comment by jarun** [comment]
Haven't noticed this yet. Feel free to close.
