### ISSUE TITLE
archlinux packaging fails

### ISSUE THREAD

**Issue by jarun** [BytePackager/packagecore#152]
I see the following error:

```
Status: Downloaded newer image for pritunl/archlinux:latest
Starting docker container 'packagecore-63a7aa7bb50b7ee7'.
5b0a345f7e69        pritunl/archlinux:latest   "tail -f /dev/null"   1 second ago        Up Less than a second                       packagecore-63a7aa7bb50b7ee7
Using shared directory '/tmp/packagecore-63a7aa7bb50b7ee7' and source directory '/tmp/packagecore-63a7aa7bb50b7ee7/src'.
:: Synchronizing package databases...
error: failed retrieving file 'core.db' from mirror.pritunl.com : The requested URL returned error: 404
error: failed to update core (unexpected error)
error: failed retrieving file 'extra.db' from mirror.pritunl.com : The requested URL returned error: 404
error: failed to update extra (unexpected error)
error: failed retrieving file 'community.db' from mirror.pritunl.com : The requested URL returned error: 404
error: failed to update community (unexpected error)
error: failed to synchronize all databases
Cleaning up self packagecore-63a7aa7bb50b7ee7.
packagecore-63a7aa7bb50b7ee7
packagecore-63a7aa7bb50b7ee7

###########################################################
# Failed to build package for 'archlinux'.
###########################################################
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/packagecore/packager.py", line 160, in run
    imageName=build["dockerImage"])
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/packagecore/packager.py", line 101, in _build
    recipe.prep(container)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/packagecore/pkgbuild.py", line 185, in prep
    "fakeroot"])
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/packagecore/docker.py", line 149, in execute
    _checkedDockerCommand(["exec", self._name] + cmd)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/packagecore/docker.py", line 54, in _checkedDockerCommand
    raise DockerError("Command '%s' returned %d." % (cmd, status))
packagecore.docker.DockerError: Command '['exec', 'packagecore-63a7aa7bb50b7ee7', 'pacman', '-Syy', '--noconfirm', 'sudo', 'binutils', 'fakeroot']' returned 1.

###########################################################
```

I have uploaded complete the logs at: http://paste.ubuntu.com/p/xgs775mvzW/

**Comment by jarun** [comment]
Hi,

Can you please take a look? I am unable to release because of this issue.

**Comment by dlasalle** [comment]
It looks like the arch linux image from pritunl is no longer maintained. Switching to a new one in #153. Will upload a new release to PYPI once the builds finish.

**Comment by jarun** [comment]
Thanks!

**Comment by dlasalle** [comment]
Just finished upload 0.9.13 to pypi.

**Comment by jarun** [comment]
Thank you!
