### ISSUE TITLE
Bad configuration file error when packaging for archlinux

### ISSUE THREAD

**Issue by jarun** [BytePackager/packagecore#160]
I see the following failure while packaging for Arch Linux:

```
[0K$ packagecore -o dist/ "${TRAVIS_TAG#v}"
args: {Namespace(configfile=None, distribution=None, outputdir='dist/', release=1, showdistributions=False, showversion=False, sourceDir='./', version='1.6')}
Building with packagecore 0.10.0.
Building version '1.6' release '1'.
DOCKER_INFO
b'Containers: 0\n Running: 0\n Paused: 0\n Stopped: 0\nImages: 0\nServer Version: 18.06.0-ce\nStorage Driver: overlay2\n Backing Filesystem: extfs\n Supports d_type: true\n Native Overlay Diff: true\nLogging Driver: json-file\nCgroup Driver: cgroupfs\nPlugins:\n Volume: local\n Network: bridge host macvlan null overlay\n Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog\nSwarm: inactive\nRuntimes: runc\nDefault Runtime: runc\nInit Binary: docker-init\ncontainerd version: d64c661f1d51c48782c9cec8fda7604785f93587\nrunc version: 69663f0bd4b60df09991c08812a60108003fa340\ninit version: fec3683\nSecurity Options:\n seccomp\n  Profile: default\nKernel Version: 4.15.0-1023-gcp\nOperating System: Ubuntu 16.04.5 LTS\nOSType: linux\nArchitecture: x86_64\nCPUs: 2\nTotal Memory: 7.298GiB\nName: travis-job-2c6eef90-4468-4379-b0b8-75f4236b39d9\nID: 5DQF:3P7R:6TTY:UNZT:5W7P:3YKK:QZFU:LFY2:ZR6A:2KKY:U4UK:VEYK\nDocker Root Dir: /var/lib/docker\nDebug Mode (client): false\nDebug Mode (server): false\nRegistry: https://index.docker.io/v1/\nLabels:\nExperimental: false\nInsecure Registries:\n 127.0.0.0/8\nLive Restore Enabled: false\n\n'
Using 'exec'
This program is licensed under the GPLv2, a copy of which is 
included with this software package.
??????????????????????????????????????????????????????
? A docker container must be specified for 'archlinux' in 
? your .yaml file using the 'container' key.
? Distributions without official containers in 
? Dockerhub now require a user specified container.
? You should only use trusted containers, as a
? maliciously configured container could be use to
? compromise your machine as well as modify the
? packages you are building.
?
? For an example of how to specify a container in a 
? .yaml filex:
? ```
? ...
? archlinux:
?   ...
?   container: example.com/myuser/my-arch-linux:latest
? ```
??????????????????????????????????????????????????????
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.7/bin/packagecore", line 11, in <module>
    sys.exit(main())
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/packagecore/__main__.py", line 130, in main
    if packager.run():
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/packagecore/packager.py", line 164, in run
    raise RuntimeError("Bad configuration file.")
RuntimeError: Bad configuration file.
travis_time:end:04a841a3:start=1542127752931908488,finish=1542127753532345654,duration=600437166
[0K[31;1mThe command "packagecore -o dist/ "${TRAVIS_TAG#v}"" failed and exited with 1 during .[0m

Your build has been stopped.
```

**Comment by dlasalle** [comment]
This was change in `0.10.0`. Because there is no `official` docker container for arch linux, I want users to explicitly choose which container to use (and thus which unofficial containers they choose to trust). See the error message in your log file:
```
??????????????????????????????????????????????????????
? A docker container must be specified for 'archlinux' in 
? your .yaml file using the 'container' key.
? Distributions without official containers in 
? Dockerhub now require a user specified container.
? You should only use trusted containers, as a
? maliciously configured container could be use to
? compromise your machine as well as modify the
? packages you are building.
?
? For an example of how to specify a container in a 
? .yaml file:
? ```
? ...
? archlinux:
?   ...
?   container: example.com/myuser/my-arch-linux:latest
? ```
??????????????????????????????????????????????????????
```
Just add the line `container: <dockerimage>` to your arch configuration. There's a number of unofficial containers on docker hub to choose from https://hub.docker.com/search/?isAutomated=1&q=archlinux

**Comment by dlasalle** [comment]
Just `container: "base/archlinux"`. If you use an image in a different registry, then you need to specify the domain. See https://docs.docker.com/engine/reference/commandline/pull/ for details (what you would use for `docker pull` is what you would use for the `container:` entry).

**Comment by jarun** [comment]
:+1:
