### ISSUE TITLE
Build for archlinux fails

### ISSUE THREAD

**Issue by jarun** [BytePackager/packagecore#169]
While generating package for `googler`, we hit the following issue:

```
Using default tag: latest
latest: Pulling from archlinux/base
Digest: sha256:f9496957524a239cf60cd0adb0a84ae633c0b712364988cd113e4fc66cdb8b7e
Status: Image is up to date for archlinux/base:latest
03a0958edf2f        archlinux/base                                                    "tail -f /dev/null"      1 second ago        Up Less than a second                                                                                                                               packagecore-a683f2c9da82979
:: Synchronizing package databases...
downloading core.db...
downloading extra.db...
downloading community.db...
resolving dependencies...
looking for conflicting packages...

Packages (3) binutils-2.31.1-4  fakeroot-1.23-1  sudo-1.8.27-1

Total Download Size:    5.62 MiB
Total Installed Size:  34.57 MiB

:: Proceed with installation? [Y/n] 
:: Retrieving packages...
downloading sudo-1.8.27-1-x86_64.pkg.tar.xz...
downloading binutils-2.31.1-4-x86_64.pkg.tar.xz...
downloading fakeroot-1.23-1-x86_64.pkg.tar.xz...
checking keyring...
checking package integrity...
loading package files...
checking for file conflicts...
checking available disk space...
:: Processing package changes...
installing sudo...
installing binutils...
installing fakeroot...
:: Running post-transaction hooks...
(1/3) Cleaning up package cache...
(2/3) Creating temporary files...
[/usr/lib/tmpfiles.d/journal-nocow.conf:26] Failed to resolve specifier: uninitialized /etc detected, skipping
All rules containing unresolvable specifiers will be skipped.
(3/3) Arming ConditionNeedsUpdate...
:: Synchronizing package databases...
downloading core.db...
downloading extra.db...
downloading community.db...
warning: archlinux-keyring-20190123-2 is up to date -- reinstalling
resolving dependencies...
looking for conflicting packages...

Packages (1) archlinux-keyring-20190123-2

Total Download Size:   0.67 MiB
Total Installed Size:  0.94 MiB
Net Upgrade Size:      0.00 MiB

:: Proceed with installation? [Y/n] warning: no /var/cache/pacman/pkg/ cache exists, creating...

:: Retrieving packages...
downloading archlinux-keyring-20190123-2-any.pkg.tar.xz...
checking keyring...
checking package integrity...
loading package files...
checking for file conflicts...
checking available disk space...
:: Processing package changes...
reinstalling archlinux-keyring...
==> Appending keys from archlinux.gpg...
==> Locally signing trusted keys in keyring...
  -> Locally signing key D8AFDDA07A5B6EDFA7D8CCDAD6D055F927843F1C...
==> ERROR: D8AFDDA07A5B6EDFA7D8CCDAD6D055F927843F1C could not be locally signed.
  -> Locally signing key DDB867B92AA789C165EEFA799B729B06A680C281...
==> ERROR: DDB867B92AA789C165EEFA799B729B06A680C281 could not be locally signed.
  -> Locally signing key 684148BB25B49E986A4944C55184252D824B18E8...
==> ERROR: 684148BB25B49E986A4944C55184252D824B18E8 could not be locally signed.
  -> Locally signing key 91FFE0700E80619CEB73235CA88E23E377514E00...
==> ERROR: 91FFE0700E80619CEB73235CA88E23E377514E00 could not be locally signed.
  -> Locally signing key 0E8B644079F599DFC1DDC3973348882F6AC6A4C2...
==> ERROR: 0E8B644079F599DFC1DDC3973348882F6AC6A4C2 could not be locally signed.
  -> Locally signing key AB19265E5D7D20687D303246BA1DFB64FFF979E7...
==> ERROR: AB19265E5D7D20687D303246BA1DFB64FFF979E7 could not be locally signed.
:: Running post-transaction hooks...
(1/2) Cleaning up package cache...
(2/2) Arming ConditionNeedsUpdate...
:: Synchronizing package databases...
downloading core.db...
downloading extra.db...
downloading community.db...
:: Starting full system upgrade...
 there is nothing to do
/tmp/packagecore-a683f2c9da82979/arch-pkg /
==> ERROR: /tmp/packagecore-a683f2c9da82979/makepkg.conf not found.
    Aborting...
/usr/sbin/makepkg: line 321: grep: command not found
/usr/sbin/makepkg: line 328: grep: command not found
packagecore-a683f2c9da82979
packagecore-a683f2c9da82979
/tmp/venv/lib/python3.6/site-packages/packagecore/configfile.py:16: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  self._data = yaml.load(yamlfile.read())
args: {Namespace(configfile=None, distributions=None, outputdir='dist', release=1, showdistributions=False, showversion=False, sourceDir='./', version='3.8')}
Building with packagecore 0.11.0.
Building version '3.8' release '1'.
DOCKER_INFO
b'Containers: 5\n Running: 3\n Paused: 0\n Stopped: 2\nImages: 68\nServer Version: 18.09.4\nStorage Driver: overlay2\n Backing Filesystem: extfs\n Supports d_type: true\n Native Overlay Diff: true\nLogging Driver: json-file\nCgroup Driver: cgroupfs\nPlugins:\n Volume: local\n Network: bridge host macvlan null overlay\n Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog\nSwarm: inactive\nRuntimes: runc\nDefault Runtime: runc\nInit Binary: docker-init\ncontainerd version: bb71b10fd8f58240ca47fbb579b9d1028eea7c84\nrunc version: 2b18fe1d885ee5083ef9f0838fee39b62d653e30\ninit version: fec3683\nSecurity Options:\n apparmor\n seccomp\n  Profile: default\nKernel Version: 4.15.0-46-generic\nOperating System: Ubuntu 18.04.2 LTS\nOSType: linux\nArchitecture: x86_64\nCPUs: 1\nTotal Memory: 1.947GiB\nName: mail.zmwang.pw\nID: IRST:FNOT:KK5F:V2IZ:J7RF:5PR4:VJ23:5FPT:ABO6:EHFX:BMZX:NODZ\nDocker Root Dir: /var/lib/docker\nDebug Mode (client): false\nDebug Mode (server): false\nUsername: zmwangx\nRegistry: https://index.docker.io/v1/\nLabels:\nExperimental: false\nInsecure Registries:\n 127.0.0.0/8\nLive Restore Enabled: false\nProduct License: Community Engine\n\n'
Using 'exec'
This program is licensed under the GPLv2, a copy of which is 
included with this software package.
Building package for archlinux: 
      name: googler
      version: 3.8
      releaseNum: 1
      maintainer: Arun Prakash Jana <engineerarun@gmail.com>
      license: GPLv3
      homepage: https://github.com/jarun/googler
      summary: Google from the command-line.
      os: archlinux
      buildDeps: ['make']
      runDeps: ['python']
      preCompileCommands: 
      compileCommands: 
      installCommands: make PREFIX="/usr" install DESTDIR="${BP_DESTDIR}"
      postInstallCommands: 
      testInstallCommands: 
      container: archlinux/base
      
Starting docker container 'packagecore-a683f2c9da82979'.
Using shared directory '/tmp/packagecore-a683f2c9da82979' and source directory '/tmp/packagecore-a683f2c9da82979/src'.
Cleaning up self packagecore-a683f2c9da82979.

###########################################################
# Failed to build package for 'archlinux'.
###########################################################
Traceback (most recent call last):
  File "/tmp/venv/lib/python3.6/site-packages/packagecore/packager.py", line 181, in run
    imageName=build["dockerImage"])
  File "/tmp/venv/lib/python3.6/site-packages/packagecore/packager.py", line 98, in _build
    recipe.build(container)
  File "/tmp/venv/lib/python3.6/site-packages/packagecore/pkgbuild.py", line 237, in build
    (self._pkgBuildDir, makePkgConf, self._data.maintainer)])
  File "/tmp/venv/lib/python3.6/site-packages/packagecore/docker.py", line 149, in execute
    _checkedDockerCommand(["exec", self._name] + cmd)
  File "/tmp/venv/lib/python3.6/site-packages/packagecore/docker.py", line 54, in _checkedDockerCommand
    raise DockerError("Command '%s' returned %d." % (cmd, status))
packagecore.docker.DockerError: Command '['exec', 'packagecore-a683f2c9da82979', '/bin/bash', '-c', "pushd '/tmp/packagecore-a683f2c9da82979/arch-pkg' && sudo -u packagecore makepkg --skipinteg --noconfirm --noprogressbar -sr --config='/tmp/packagecore-a683f2c9da82979/makepkg.conf' PACKAGER='abc def <xxxx@gmail.com>' && popd"]' returned 2.

###########################################################
```

From yaml file:

```
archlinux:		
     builddeps:		
       - make		
     deps:		
       - python		
     container: "archlinux/base"
```

**Comment by dlasalle** [comment]
I am unable to reproduce this issue currently. Can you try re-running and let me know if it works with the latest archlinux docker image, or if the problem persists?

**Comment by dlasalle** [comment]
If you can confirm that this isn't an issue anymore, I'll look at cutting a new release with the fixes for #170 and #171.

**Comment by jarun** [comment]
This is probably fixed now given I could package another utility `pdd` for Arch after this failure.

**Comment by jarun** [comment]
Closing the issue with the above comment.
