### ISSUE TITLE
Package for ubuntu17.10 fails to get build by travis-ci

### ISSUE THREAD

**Issue by dlasalle** [BytePackager/packagecore#79]
```
running python post-rtupdate hooks for python3.5...

Setting up python3-pkg-resources (36.0.1-1) ...

Setting up python3-setuptools (36.0.1-1) ...

Setting up dh-python (2.20170125) ...

Setting up python3-yaml (3.12-1build1) ...

Processing triggers for libc-bin (2.24-9ubuntu2) ...

Processing triggers for sgml-base (1.29) ...

Selecting previously unselected package packagecore.
(Reading database ... 5997 files and directories currently installed.)
Preparing to unpack .../packagecore_0.9.2-1_amd64.deb ...
Unpacking packagecore (0.9.2-1) ...
Setting up packagecore (0.9.2-1) ...
Traceback (most recent call last):
  File "/usr/bin/packagecore", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3037, in <module>
    @_call_aside
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3021, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3050, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 655, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 969, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 855, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'packagecore==0.9.2' distribution was not found and is required by the application
```

**Comment by dlasalle** [comment]
This is due to the package installing into `site-packages`, when ubuntu is using `dist-packages`.

**Comment by dlasalle** [comment]
The fix is to specify `--install-layout` which is available as part of the ubuntu/debian setuptools module.
